apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: myapp
  template:
    metadata:
      labels:
        app: myapp
    spec:
      containers:
      - name: myapp
        image: cortanexai.com:5000/ops:latest
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: nexus-creds
