name: Build & Deploy to Dev
on:
  push:
    branches:
      - main

env:
  IMAGE_NAME: ops
  REGISTRY: cortanexai.com:5000

jobs:
  build-and-promote:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure insecure registry
        run: |
          echo '{ "insecure-registries":["cortanexai.com:5000"] }' | sudo tee /etc/docker/daemon.json
          sudo systemctl restart docker
      - name: Log in to Nexus
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ secrets.NEXUS_USERNAME }}
          password: ${{ secrets.NEXUS_PASSWORD }}

      - name: Build & Push Image (dev)
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev

      - name: Update kustomization (dev)
        run: |
          cd k8s/overlays/dev
          kustomize edit set image ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:dev
          git config user.name "ahmadmajdi96"
          git config user.email "ahmad.majdi96@gmail.com"
          git commit -am "ci: update dev image"
          git push

permissions:
  contents: write
